# Lagbuster Configuration Example
# Copy this file to config.yaml and customize for your environment

# Edge router peers to monitor
peers:
  - name: edge01
    hostname: edge01.example.com
    expected_baseline: 45.0  # milliseconds - your expected "good" latency
    bird_variable: core01_edge01_lagbuster_priority

  - name: edge02
    hostname: edge02.example.com
    expected_baseline: 55.0  # milliseconds
    bird_variable: core01_edge02_lagbuster_priority

  - name: edge03
    hostname: edge03.example.com
    expected_baseline: 52.0  # milliseconds
    bird_variable: core01_edge03_lagbuster_priority

# Health check thresholds
thresholds:
  # Switch away from current primary if it degrades by this much from its baseline
  degradation_threshold: 20.0  # milliseconds

  # Stay on current primary if within this comfort zone above baseline
  comfort_threshold: 10.0  # milliseconds

  # Hard limit - any peer exceeding this is considered unhealthy regardless of baseline
  absolute_max_latency: 150.0  # milliseconds

  # Treat ping timeout as this value for comparison
  timeout_latency: 3000.0  # milliseconds

# Damping settings to prevent route flapping
damping:
  # Require this many consecutive unhealthy measurements before switching away from current primary
  consecutive_unhealthy_count: 3

  # How often to measure latency
  measurement_interval: 10  # seconds

  # Minimum time between switches (cooldown period)
  cooldown_period: 180  # seconds (3 minutes)

  # Size of rolling window for tracking measurements per peer
  measurement_window: 20  # number of measurements to keep

# Startup behavior
startup:
  # Wait this long before making first priority change (allows baselines to stabilize)
  grace_period: 60  # seconds

  # Initial primary peer (by name) - will be used until grace period expires
  initial_primary: edge01

  # Preferred primary for automatic failback (optional)
  # If set and failback is enabled, lagbuster will automatically switch back to this peer
  # after it has been healthy for the configured duration
  preferred_primary: edge01  # must match a peer name above

# Automatic failback to preferred primary
failback:
  # Enable automatic failback to preferred primary when it recovers
  enabled: true

  # Number of consecutive healthy measurements required before failing back
  # With measurement_interval=10s, 180 measurements = 30 minutes of sustained health
  consecutive_healthy_count: 180  # measurements (e.g., 180 × 10s = 30 minutes)

  # Wait for cooldown period to complete before allowing failback
  # If false, failback can happen immediately after consecutive_healthy_count is reached
  # If true, must also wait cooldown_period seconds since last switch
  require_cooldown_before_failback: true

# Bird integration
bird:
  # Path to lagbuster-managed priorities file
  priorities_file: /etc/bird/lagbuster-priorities.conf

  # Path to birdc binary
  birdc_path: /usr/sbin/birdc

  # Timeout for birdc commands
  birdc_timeout: 5  # seconds

# Logging
logging:
  # Log level: debug, info, warn, error
  level: info

  # Log all latency measurements (can be verbose)
  log_measurements: false

  # Log decision rationale
  log_decisions: true

# Operational mode
mode:
  # Set to true to log decisions without actually applying changes
  dry_run: false

# Web API and monitoring
api:
  # Enable HTTP API and WebSocket for real-time monitoring
  enabled: true

  # Address and port to listen on
  listen_address: "0.0.0.0:8080"

# Database for historical metrics and events
database:
  # Path to SQLite database file (leave empty to disable)
  path: "/var/lib/lagbuster/lagbuster.db"

  # Days to retain historical data (0 = keep forever)
  retention_days: 30

# Notifications
notifications:
  # Enable notification system
  enabled: true

  # Rate limit: minimum minutes between notifications of same type to same channel
  rate_limit_minutes: 5

  # Email notifications via SMTP
  email:
    enabled: false
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    username: "your-email@gmail.com"
    password: "your-app-password"  # Use app-specific password for Gmail
    from: "lagbuster@example.com"
    to:
      - "ops@example.com"
      - "oncall@example.com"
    # Event types to notify about
    events:
      - "switch"
      - "failback"
      - "unhealthy"

  # Slack notifications via webhook
  slack:
    enabled: false
    webhook_url: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
    events:
      - "switch"
      - "failback"
      - "unhealthy"
      - "recovery"

  # Telegram notifications via bot
  telegram:
    enabled: false
    bot_token: "YOUR_BOT_TOKEN"
    chat_id: "YOUR_CHAT_ID"
    events:
      - "switch"
      - "failback"
      - "unhealthy"
      - "recovery"
      - "startup"
      - "shutdown"
